-- =============================================================
-- Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
-- Erik Shop 简化版 (Lite) — 25张核心表
-- =============================================================
SET NAMES utf8mb4; SET FOREIGN_KEY_CHECKS = 0;

-- 用户
CREATE TABLE erik_users (
    id BIGINT UNSIGNED NOT NULL COMMENT 'snowflake主键',
    nickname VARCHAR(64) NOT NULL DEFAULT '', avatar VARCHAR(512) NOT NULL DEFAULT '',
    email VARCHAR(256) NOT NULL DEFAULT '' COMMENT '邮箱(加密)', mobile VARCHAR(64) NOT NULL DEFAULT '' COMMENT '手机(加密)',
    password VARCHAR(256) NOT NULL DEFAULT '', salt CHAR(6) NOT NULL DEFAULT '',
    sex TINYINT UNSIGNED NOT NULL DEFAULT 0, birthday DATE NULL,
    money DECIMAL(12,2) NOT NULL DEFAULT 0.00, score INT UNSIGNED NOT NULL DEFAULT 0,
    level TINYINT UNSIGNED NOT NULL DEFAULT 0, status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    last_login_at DATETIME NULL, last_login_ip VARCHAR(45) NOT NULL DEFAULT '',
    invite_code VARCHAR(16) NOT NULL DEFAULT '', inviter_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uk_invite_code (invite_code), KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE erik_user_addresses (
    id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(128) NOT NULL DEFAULT '', phone VARCHAR(64) NOT NULL DEFAULT '',
    country_id BIGINT UNSIGNED NOT NULL DEFAULT 0, province VARCHAR(128) NOT NULL DEFAULT '',
    city VARCHAR(128) NOT NULL DEFAULT '', district VARCHAR(128) NOT NULL DEFAULT '',
    detail VARCHAR(512) NOT NULL DEFAULT '', postal_code VARCHAR(20) NOT NULL DEFAULT '',
    is_default TINYINT UNSIGNED NOT NULL DEFAULT 0, tag VARCHAR(32) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户地址';

-- 分类
CREATE TABLE erik_categories (
    id BIGINT UNSIGNED NOT NULL, parent_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL, slug VARCHAR(128) NOT NULL DEFAULT '',
    icon VARCHAR(512) NOT NULL DEFAULT '', image VARCHAR(512) NOT NULL DEFAULT '',
    sort INT UNSIGNED NOT NULL DEFAULT 0, status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    is_hot TINYINT UNSIGNED NOT NULL DEFAULT 0, level TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), KEY idx_parent_id (parent_id), KEY idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='分类表';

-- 商品
CREATE TABLE erik_products (
    id BIGINT UNSIGNED NOT NULL, category_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    title VARCHAR(256) NOT NULL DEFAULT '', subtitle VARCHAR(256) NOT NULL DEFAULT '',
    slug VARCHAR(256) NOT NULL DEFAULT '', brand VARCHAR(128) NOT NULL DEFAULT '',
    main_image VARCHAR(512) NOT NULL DEFAULT '', video_url VARCHAR(512) NOT NULL DEFAULT '',
    description TEXT, status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0草稿/1待审/2上架/3下架',
    is_hot TINYINT UNSIGNED NOT NULL DEFAULT 0, is_new TINYINT UNSIGNED NOT NULL DEFAULT 0,
    is_recommend TINYINT UNSIGNED NOT NULL DEFAULT 0, sort INT UNSIGNED NOT NULL DEFAULT 0,
    sales_count INT UNSIGNED NOT NULL DEFAULT 0, view_count INT UNSIGNED NOT NULL DEFAULT 0,
    min_price DECIMAL(12,2) NOT NULL DEFAULT 0.00, max_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    weight DECIMAL(10,2) NOT NULL DEFAULT 0.00, unit VARCHAR(16) NOT NULL DEFAULT 'piece',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), KEY idx_category_id (category_id), KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品表';

CREATE TABLE erik_product_skus (
    id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL,
    sku_code VARCHAR(64) NOT NULL, attrs JSON COMMENT '属性',
    default_price DECIMAL(12,2) NOT NULL DEFAULT 0.00, origin_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    cost_price DECIMAL(12,2) NOT NULL DEFAULT 0.00, stock INT NOT NULL DEFAULT 0,
    stock_warning INT UNSIGNED NOT NULL DEFAULT 10, image VARCHAR(512) NOT NULL DEFAULT '',
    status TINYINT UNSIGNED NOT NULL DEFAULT 1, sales_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uk_sku_code (sku_code), KEY idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SKU';

CREATE TABLE erik_product_images (
    id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL,
    url VARCHAR(512) NOT NULL, sort INT UNSIGNED NOT NULL DEFAULT 0, is_main TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), KEY idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品图片';

CREATE TABLE erik_product_reviews (
    id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL,
    order_id BIGINT UNSIGNED NOT NULL DEFAULT 0, sku_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    rating TINYINT UNSIGNED NOT NULL COMMENT '1-5', content TEXT, images JSON,
    is_anonymous TINYINT UNSIGNED NOT NULL DEFAULT 0, status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    reply_content TEXT, reply_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), KEY idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品评价';

-- 购物车+订单
CREATE TABLE erik_carts (
    id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
    sku_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL,
    quantity INT UNSIGNED NOT NULL DEFAULT 1, selected TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uk_user_sku (user_id, sku_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='购物车';

CREATE TABLE erik_orders (
    id BIGINT UNSIGNED NOT NULL, order_no VARCHAR(32) NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0待付款/1已付款/2已发货/3已收货/4已完成/5已取消',
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00, discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    shipping_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00, pay_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD', pay_method VARCHAR(32) NOT NULL DEFAULT '',
    pay_at DATETIME NULL, shipping_at DATETIME NULL, received_at DATETIME NULL, canceled_at DATETIME NULL,
    remark VARCHAR(512) NOT NULL DEFAULT '', address_snapshot JSON,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uk_order_no (order_no), KEY idx_user_id (user_id), KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表';

CREATE TABLE erik_order_items (
    id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL, sku_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(256) NOT NULL, image VARCHAR(512) NOT NULL DEFAULT '',
    sku_attrs_snapshot JSON, price DECIMAL(12,2) NOT NULL, quantity INT UNSIGNED NOT NULL DEFAULT 1,
    subtotal DECIMAL(12,2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id), KEY idx_order_id (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单明细';

CREATE TABLE erik_order_logs (
    id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NOT NULL,
    from_status TINYINT NOT NULL DEFAULT -1, to_status TINYINT NOT NULL,
    operator VARCHAR(64) NOT NULL DEFAULT 'system', remark VARCHAR(256) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), KEY idx_order_id (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单日志';

CREATE TABLE erik_payments (
    id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
    gateway VARCHAR(32) NOT NULL, method VARCHAR(32) NOT NULL DEFAULT '',
    transaction_no VARCHAR(256) NOT NULL DEFAULT '', amount DECIMAL(12,2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD', status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0待付/1已付/2已退/3失败',
    paid_at DATETIME NULL, refunded_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00, gateway_data JSON,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id), UNIQUE KEY uk_transaction_no (transaction_no), KEY idx_order_id (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付记录';

CREATE TABLE erik_refunds (
    id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
    refund_no VARCHAR(32) NOT NULL, type TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1仅退款/2退货退款',
    amount DECIMAL(12,2) NOT NULL, reason VARCHAR(256) NOT NULL DEFAULT '', images JSON,
    status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0待审/1通过/2驳回/3已退款',
    reject_reason VARCHAR(256) NOT NULL DEFAULT '', refunded_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uk_refund_no (refund_no), KEY idx_order_id (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退款表';

-- 营销+运营
CREATE TABLE erik_coupons (
    id BIGINT UNSIGNED NOT NULL, title VARCHAR(128) NOT NULL,
    type TINYINT UNSIGNED NOT NULL COMMENT '1满减/2折扣/3固定', value DECIMAL(10,2) NOT NULL,
    min_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00, total_qty INT UNSIGNED NOT NULL,
    received_qty INT UNSIGNED NOT NULL DEFAULT 0, used_qty INT UNSIGNED NOT NULL DEFAULT 0,
    per_user_limit INT UNSIGNED NOT NULL DEFAULT 1, start_at DATETIME NULL, end_at DATETIME NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='优惠券';

CREATE TABLE erik_user_coupons (
    id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, coupon_id BIGINT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0未用/1已用/2过期',
    used_at DATETIME NULL, used_order_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id), KEY idx_user_coupon (user_id, coupon_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户优惠券';

CREATE TABLE erik_banners (
    id BIGINT UNSIGNED NOT NULL, title VARCHAR(128) NOT NULL DEFAULT '',
    image VARCHAR(512) NOT NULL, link_url VARCHAR(512) NOT NULL DEFAULT '',
    position VARCHAR(32) NOT NULL DEFAULT 'home', sort INT UNSIGNED NOT NULL DEFAULT 0,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1, start_at DATETIME NULL, end_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), KEY idx_position_status (position, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='轮播图';

CREATE TABLE erik_notifications (
    id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0=全部',
    title VARCHAR(256) NOT NULL, content TEXT, type VARCHAR(32) NOT NULL DEFAULT 'system',
    target_type VARCHAR(32) NOT NULL DEFAULT '', target_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    is_read TINYINT UNSIGNED NOT NULL DEFAULT 0, read_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), KEY idx_user_read (user_id, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知';

CREATE TABLE erik_settings (
    id BIGINT UNSIGNED NOT NULL, `key` VARCHAR(64) NOT NULL, value TEXT,
    `group` VARCHAR(32) NOT NULL DEFAULT 'general', remark VARCHAR(256) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id), UNIQUE KEY uk_key (`key`), KEY idx_group (`group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统配置';

CREATE TABLE erik_operation_logs (
    id BIGINT UNSIGNED NOT NULL, admin_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    module VARCHAR(32) NOT NULL, action VARCHAR(32) NOT NULL, target_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    content JSON, ip VARCHAR(45) NOT NULL DEFAULT '', user_agent VARCHAR(512) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), KEY idx_admin_id (admin_id), KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志';

CREATE TABLE erik_search_logs (
    id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    keyword VARCHAR(256) NOT NULL, result_count INT UNSIGNED NOT NULL DEFAULT 0,
    locale VARCHAR(10) NOT NULL DEFAULT 'en',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), KEY idx_keyword (keyword(64)), KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='搜索日志';

-- 基础数据
CREATE TABLE erik_countries (
    id BIGINT UNSIGNED NOT NULL, name_en VARCHAR(128) NOT NULL, name_cn VARCHAR(128) NOT NULL DEFAULT '',
    iso_code_2 CHAR(2) NOT NULL, iso_code_3 CHAR(3) NOT NULL DEFAULT '',
    phone_code VARCHAR(8) NOT NULL DEFAULT '', currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    flag_emoji VARCHAR(8) NOT NULL DEFAULT '', timezone VARCHAR(32) NOT NULL DEFAULT '',
    status TINYINT UNSIGNED NOT NULL DEFAULT 1, sort INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uk_iso_code_2 (iso_code_2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='国家/地区';

CREATE TABLE erik_currencies (
    id BIGINT UNSIGNED NOT NULL, code CHAR(3) NOT NULL, name VARCHAR(64) NOT NULL,
    symbol VARCHAR(8) NOT NULL DEFAULT '', is_default TINYINT UNSIGNED NOT NULL DEFAULT 0,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uk_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='货币';

CREATE TABLE erik_exchange_rates (
    id BIGINT UNSIGNED NOT NULL, from_currency CHAR(3) NOT NULL, to_currency CHAR(3) NOT NULL,
    rate DECIMAL(18,8) NOT NULL, source VARCHAR(32) NOT NULL DEFAULT 'manual',
    effective_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id), KEY idx_from_to (from_currency, to_currency)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='汇率';

SET FOREIGN_KEY_CHECKS = 1;
